name 'apache'
maintainer 'srikanth'
maintainer_email 'sriredspot@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
